assetic:
    bundles:
        - 'EzPlatformFormBuilderMaskedInputBundle'

twig:
    form_themes:
        - '@EzPlatformFormBuilderMaskedInput/form/fields.html.twig'

ez_platform_form_builder:
    fields:
        masked:
            name: 'Masked'
            category: 'Basic form fields'
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#input-line'
            attributes:
                mask:
                    name: 'Mask'
                    type: 'string'
                greedy:
                    name: 'Greedy'
                    type: 'checkbox'
            validators:
                required: ~
